"""empty message

Revision ID: 36772182fa5e
Revises: b009818c6db0
Create Date: 2020-06-25 16:40:21.998108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36772182fa5e'
down_revision = 'b009818c6db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clients', 'adress', ['fk_adress_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    # ### end Alembic commands ###
