"""empty message

Revision ID: 6041d08f0f23
Revises: 92b0937dbde2
Create Date: 2020-06-23 18:56:46.080824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6041d08f0f23'
down_revision = '92b0937dbde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_ibfk_1', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'adress', ['fk_adress_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_ibfk_1', 'clients', 'adress', ['fk_adress_id'], ['id'])
    # ### end Alembic commands ###
