"""empty message

Revision ID: 63829c9e8576
Revises: d94d5049cc2f
Create Date: 2020-06-21 17:44:29.269143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63829c9e8576'
down_revision = 'd94d5049cc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['cpf'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
