"""empty message

Revision ID: bc23efb1bb3d
Revises: aa35a3d5f616
Create Date: 2020-06-07 16:23:27.648098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc23efb1bb3d'
down_revision = 'aa35a3d5f616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'password')
    # ### end Alembic commands ###
