"""empty message

Revision ID: d94d5049cc2f
Revises: aa35a3d5f616
Create Date: 2020-06-21 17:28:39.255752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94d5049cc2f'
down_revision = 'aa35a3d5f616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('password', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'employers', ['cpf'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employers', type_='unique')
    op.drop_column('employers', 'password')
    # ### end Alembic commands ###
